name: Autocoder Bot Workflow
on: 
  issues:    
    types: [opened, reopened, labeled]
jobs: 
  auto-coder:
    runs-on: ubuntu-latest
    steps:
      - if: containcontains(github.event.issue.labels.*.name, 'autocoder-bot')
        name: Generate Code with ChatGPT
        id: generate_code
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: chmod +x ./scripts/script.sh && ./scripts/script.sh ${{ env.GITHUB_TOKEN }} ${{env.REPOSITORY}} ${{env.ISSUE_NUMBER}} ${{ env.OPENAI_API_KEY }} > output.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: autocoder-artifact
          path: output.txt
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-artifact
      - name: Display Generated Code using the ls command
        run: ls -R autocoder-artifact
    # output code
